# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container at /app
COPY target/product-service.jar /app

# Expose the port that the application runs on
EXPOSE 8080

# Specify the command to run on container startup
CMD ["java", "-jar", "product-service.jar"]