server:
  port: 8080
  error:
    include-stacktrace: ON_PARAM
spring:
  datasource:
    url: jdbc:mysql://localhost:3309/product-service
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 10000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect