# Use a base image with OpenJDK
FROM openjdk:11

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container at /app
COPY target/cart-service.jar /app

# Expose the port that the application runs on
EXPOSE 8080

# Specify the command to run on container startup
CMD ["java", "-jar", "cart-service.jar"]